name: code-challenge
services:
  node:
    build:
      context: ../
      dockerfile: docker/node/Dockerfile
    container_name: code-challenge-node
    volumes:
      - ../node:/home/node/app
    ports:
      - 8080:8080
    environment:
      DB_CONNECTION_STRING: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: code-challenge-db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
      POSTGRES_DB: ${DB_NAME:?}
    healthcheck:
      test: "pg_isready --username=admin --dbname=code-challenge"
      timeout: 10s
      retries: 20
    ports:
      - 5433:5432
